# Generated by Django 5.2.3 on 2025-08-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_candidate_userprofile_delete_category_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_registered_voter',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('Manila', 'Manila'), ('Cebu City', 'Cebu City'), ('Davao City', 'Davao City'), ('Baguio', 'Baguio'), ('Iloilo City', 'Iloilo City')], default='Manila', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Other', max_length=1),
        ),
    ]
